# Generated by Django 2.2.13 on 2020-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
